# --- IPPO specific parameters ---
action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 100000
mask_before_softmax: True

mac: 'basic_mac'
agent: 'n_rnn'
runner: 'parallel'
t_max: 10000000

buffer_size: 64
batch_size_run: 8
batch_size: 64

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.001
hidden_dim: 64

obs_agent_id: True

critic_coef: 0.5
entropy: 0.1
gae_lambda: 0.95
mini_epochs: 8
eps_clip: 0.1
save_probs: True


agent_output_type: "pi_logits"
learner: "ppo_learner"
critic_type: "ac_critic"


use_layer_norm: True
use_orthogonal: True
gain: 0.01
use_value_norm: True

name: "ippo"

