# --- IQL specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 5000000
evaluation_epsilon: 0.0
runner: "parallel"
batch_size_run: 8


buffer_size: 5000

target_update_interval_or_tau: 100

lr: 0.001
hidden_dim: 64


# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"

double_q: True
mixer: # Mixer becomes None

name: "iql"