# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 5000000
evaluation_epsilon: 0.0

batch_size_run: 8 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000 
batch_size: 128
runner: "parallel"

# update the tget network every {} episodes
target_update_interval_or_tau: 100

# use the Q_Learner to train
mac: "n_mac"
agent: "n_rnn"
agent_output_type: q
learner: "q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32

lr: 0.001 # Learning rate for agents

# rnn layer normalization
use_layer_norm: False

# orthogonal init for DNN
use_orthogonal: False
gain: 0.01

hypernet_layers: 2
hypernet_embed: 64

name: "qmix"
