
# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 5000000
evaluation_epsilon: 0.0

runner: "parallel"
batch_size_run: 8 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000 
batch_size: 128

# update the target network every {} episodes
target_update_interval: 200

mac: "n_mac"
agent: "n_rnn"
agent_output_type: q

learner: "nq_learner"
double_q: True
mixer: "vdn"
mixing_embed_dim: 32
hypernet_embed: 64
td_lambda: 0.6
q_lambda: False
lr: 0.001

# orthogonal init for DNN
use_orthogonal: False
gain: 0.01

# rnn layer normalization
use_layer_norm: False

name: "vdn"