exclude: null
grid-search:

  "--config":
    - "vdn"

  lr:
    - 0.001
    - 0.0005





  epsilon_anneal_time:
    - 5000000

    
grid-search-groups:
  env0:
    - "--env-config": "overcooked2"
    - env_args.map_name: supereasy
    - env_args.ifrender: False
